spring.application.name=DynoCloud

spring.profiles.active=local


garage.endpoint=${GARAGE_ENDPOINT}
garage.region=${GARAGE_REGION:us-east-1}
garage.access-key=${GARAGE_ACCESS_KEY}
garage.secret-key=${GARAGE_SECRET_KEY}
garage.bucket=dynocloud-files